//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - PSDE_SC
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "PSDE_SC", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IPSDE_SC 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "registrar_categoriausuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS registrar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "modificar_categoriausuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS modificar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "eliminar_categoriausuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS eliminar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "buscar_categoriausuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS buscar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "agregar_fuente_financiamiento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS agregar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "elminar_fuente_financiamiento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS elminar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "modificar_fuente_financiamiento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS modificar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Departamento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DepartamentoRS Agregar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Departamento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DepartamentoRS Modificar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Departamento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DepartamentoRS Eliminar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "BuscarDepartamento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DepartamentoRS BuscarDepartamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Municipio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.MunicipioRS Agregar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Municipio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.MunicipioRS Modificar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Municipio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.MunicipioRS Eliminar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Buscar_Municipio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.MunicipioRS Buscar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Sucursal", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SucursalRS Agregar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Sucursal", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SucursalRS Modificar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Sucursal", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SucursalRS Eliminar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "modificar_indicador", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.IndicadorRS modificar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "eliminar_indicador", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.IndicadorRS eliminar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "registrar_indicador", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.IndicadorRS registrar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "buscar_indicador", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.IndicadorRS buscar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_SectorProductivo", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SectorProductivoRS Agregar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_SectorProductivo", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SectorProductivoRS Modificar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_SectorProductivo", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SectorProductivoRS Eliminar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Buscar_SectorProductivo", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.SectorProductivoRS Buscar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_ProductoFinanciero", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ProductoFinancierRS Agregar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_ProductoFinanciero", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ProductoFinancierRS Modificar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_ProductoFinanciero", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ProductoFinancierRS Eliminar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Buscar_ProductoFinanciero", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ProductoFinancierRS Buscar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Usuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.UsuarioRS Agregar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Usuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.UsuarioRS Eliminar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Usuario", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.UsuarioRS Modificar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_TipoEvento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.TipoEventoRS Agregar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_TipoEvento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.TipoEventoRS Eliminar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_TipoEvento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.TipoEventoRS Modificar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Evento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.EventoRS Agregar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Evento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.EventoRS Modificar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Evento", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.EventoRS Eliminar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Convenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ConvenioRS Modificar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Convenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ConvenioRS Agregar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Convenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ConvenioRS Eliminar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_DetalleConvenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DetalleConvenioRS Agregar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_DetalleConvenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DetalleConvenioRS Modificar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_DetalleConvenio", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.DetalleConvenioRS Eliminar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Finca", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FincaRS Agregar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Finca", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FincaRS Modificar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Finca", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FincaRS Eliminar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Buscar_Finca", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.FincaRS Buscar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://PSDE.Model/2013/PSDE_SC/PSDE_SC/Agregar_Historial", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.HistorialRS Agregar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://PSDE.Model/2013/PSDE_SC/PSDE_SC/Modificar_Historial", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.HistorialRS Modificar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://PSDE.Model/2013/PSDE_SC/PSDE_SC/Eliminar_Historial", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.HistorialRS Eliminar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://PSDE.Model/2013/PSDE_SC/PSDE_SC/Buscar_Historial", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.HistorialRS Buscar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Cliente", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ClienteRS Modificar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Cliente", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ClienteRS Agregar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Cliente", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ClienteRS Eliminar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Agregar_Contrato", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ContratoRS Agregar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_Contrato", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ContratoRS Modificar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_Contrato", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.ContratoRS Eliminar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "registrar_general_detalle", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralDetalleRS registrar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "eliminar_general_detalle", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralDetalleRS eliminar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "modificar_general_detalle", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralDetalleRS modificar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "buscar_general_detalle", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralDetalleRS buscar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Registrar_General", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralRS Registrar_General(PSDE_SERVICE.MessageContracts.GeneralRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Modificar_General", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralRS Modificar_General(PSDE_SERVICE.MessageContracts.GeneralRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Eliminar_General", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralRS Eliminar_General(PSDE_SERVICE.MessageContracts.GeneralRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "Buscar_General", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.GeneralRS Buscar_General(PSDE_SERVICE.MessageContracts.GeneralRQ request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "CargarClientes", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CargarClientesRS CargarClientes();
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "CargarMunicipios", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CargaMunicipiosRS CargarMunicipios();
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "CargarUsuarios", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CargarUsuariosRS CargarUsuarios();
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "CargarCategorias", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CargarCategoriasRS CargarCategorias();
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "CargarEventos", ProtectionLevel = ProtectionLevel.None)]
		PSDE_SERVICE.MessageContracts.CargarEventosRS CargarEventos();
		
	}
}

