
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CargarCategoriasRS
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CargarCategoriasRS
	{
		private PSDE_SERVICE.DataContracts.CategoriasUsuarios categorias;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "Categorias")]
		public PSDE_SERVICE.DataContracts.CategoriasUsuarios Categorias
		{
			get { return categorias; }
			set { categorias = value; }
		}
	}
}

