
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CargarUsuariosRS
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CargarUsuariosRS
	{
		private PSDE_SERVICE.DataContracts.ListaVistaUsuarios usuarios;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "Usuarios")]
		public PSDE_SERVICE.DataContracts.ListaVistaUsuarios Usuarios
		{
			get { return usuarios; }
			set { usuarios = value; }
		}
	}
}

