
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CargarFincaRS
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CargarFincaRS
	{
		private PSDE_SERVICE.DataContracts.ListaVistaFincas fincas;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "Fincas")]
		public PSDE_SERVICE.DataContracts.ListaVistaFincas Fincas
		{
			get { return fincas; }
			set { fincas = value; }
		}
	}
}

