
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CategoriaUsuarioRQ
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CategoriaUsuarioRQ
	{
		private PSDE_SERVICE.DataContracts.CategoriaUsuario categoriaUsuario;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "CategoriaUsuario")]
		public PSDE_SERVICE.DataContracts.CategoriaUsuario CategoriaUsuario
		{
			get { return categoriaUsuario; }
			set { categoriaUsuario = value; }
		}
	}
}

