
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - CoordenadaRQ
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class CoordenadaRQ
	{
		private PSDE_SERVICE.DataContracts.Coordenada coordenada;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "Coordenada")]
		public PSDE_SERVICE.DataContracts.Coordenada Coordenada
		{
			get { return coordenada; }
			set { coordenada = value; }
		}
	}
}

