
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - DetalleConvenioRQ
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class DetalleConvenioRQ
	{
		private PSDE_SERVICE.DataContracts.DetalleConvenio detalleConvenio;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "DetalleConvenio")]
		public PSDE_SERVICE.DataContracts.DetalleConvenio DetalleConvenio
		{
			get { return detalleConvenio; }
			set { detalleConvenio = value; }
		}
	}
}

