
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ProductoFinancieroRQ
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class ProductoFinancieroRQ
	{
		private PSDE_SERVICE.DataContracts.ProductoFinanciero productoFinanciero;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "ProductoFinanciero")]
		public PSDE_SERVICE.DataContracts.ProductoFinanciero ProductoFinanciero
		{
			get { return productoFinanciero; }
			set { productoFinanciero = value; }
		}
	}
}

