
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace PSDE_SERVICE.MessageContracts
{
	/// <summary>
	/// Service Contract Class - SectorProductivoRQ
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class SectorProductivoRQ
	{
		private PSDE_SERVICE.DataContracts.SectorProductivo sectorProductivo;
	 		
		[WCF::MessageBodyMember(Namespace = "http://PSDE.Model/2013/PSDE_SC", Name = "SectorProductivo")]
		public PSDE_SERVICE.DataContracts.SectorProductivo SectorProductivo
		{
			get { return sectorProductivo; }
			set { sectorProductivo = value; }
		}
	}
}

