//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;
using System.Data;

namespace PSDE_SERVICE.ServiceImplementation
{	
	/// <summary>
	/// Service Class - PSDE_S
	/// </summary>
	[WCF::ServiceBehavior(Name = "PSDE_S", 
		Namespace = "http://PSDE.Model/2013/PSDE_SC", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Multiple )]
	public abstract class PSDE_SBase : PSDE_SERVICE.ServiceContracts.IPSDE_SC
	{
		#region PSDE_SC Members

		public virtual PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS registrar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS modificar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS eliminar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CategoriaUsuarioRS buscar_categoriausuario(PSDE_SERVICE.MessageContracts.CategoriaUsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS agregar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS elminar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRS modificar_fuente_financiamiento(PSDE_SERVICE.MessageContracts.FuenteFinanciamientoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DepartamentoRS Agregar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DepartamentoRS Modificar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DepartamentoRS Eliminar_Departamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DepartamentoRS BuscarDepartamento(PSDE_SERVICE.MessageContracts.DepartamentoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.MunicipioRS Agregar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.MunicipioRS Modificar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.MunicipioRS Eliminar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.MunicipioRS Buscar_Municipio(PSDE_SERVICE.MessageContracts.MunicipioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SucursalRS Agregar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SucursalRS Modificar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SucursalRS Eliminar_Sucursal(PSDE_SERVICE.MessageContracts.SucursalRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.IndicadorRS modificar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.IndicadorRS eliminar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.IndicadorRS registrar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.IndicadorRS buscar_indicador(PSDE_SERVICE.MessageContracts.IndicadorRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SectorProductivoRS Agregar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SectorProductivoRS Modificar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SectorProductivoRS Eliminar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.SectorProductivoRS Buscar_SectorProductivo(PSDE_SERVICE.MessageContracts.SectorProductivoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ProductoFinancierRS Agregar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ProductoFinancierRS Modificar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ProductoFinancierRS Eliminar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ProductoFinancierRS Buscar_ProductoFinanciero(PSDE_SERVICE.MessageContracts.ProductoFinancieroRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.UsuarioRS Agregar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.UsuarioRS Eliminar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.UsuarioRS Modificar_Usuario(PSDE_SERVICE.MessageContracts.UsuarioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.TipoEventoRS Agregar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.TipoEventoRS Eliminar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.TipoEventoRS Modificar_TipoEvento(PSDE_SERVICE.MessageContracts.TipoEventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.EventoRS Agregar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.EventoRS Modificar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.EventoRS Eliminar_Evento(PSDE_SERVICE.MessageContracts.EventoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ConvenioRS Modificar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ConvenioRS Agregar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ConvenioRS Eliminar_Convenio(PSDE_SERVICE.MessageContracts.ConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DetalleConvenioRS Agregar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DetalleConvenioRS Modificar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.DetalleConvenioRS Eliminar_DetalleConvenio(PSDE_SERVICE.MessageContracts.DetalleConvenioRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FincaRS Agregar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FincaRS Modificar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FincaRS Eliminar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.FincaRS Buscar_Finca(PSDE_SERVICE.MessageContracts.FincaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.HistorialRS Agregar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.HistorialRS Modificar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.HistorialRS Eliminar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.HistorialRS Buscar_Historial(PSDE_SERVICE.MessageContracts.HistorialRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CoordenadaRS Agregar_Coordenada(PSDE_SERVICE.MessageContracts.CoordenadaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CoordenadaRS Modificar_Coordenada(PSDE_SERVICE.MessageContracts.CoordenadaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.CoordenadaRS Eliminar_Coordenada(PSDE_SERVICE.MessageContracts.CoordenadaRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ClienteRS Modificar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ClienteRS Agregar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ClienteRS Eliminar_Cliente(PSDE_SERVICE.MessageContracts.ClienteRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ContratoRS Agregar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ContratoRS Modificar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.ContratoRS Eliminar_Contrato(PSDE_SERVICE.MessageContracts.ContratoRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.GeneralDetalleRS registrar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.GeneralDetalleRS eliminar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.GeneralDetalleRS modificar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request)
		{
			return null;
		}

		public virtual PSDE_SERVICE.MessageContracts.GeneralDetalleRS buscar_general_detalle(PSDE_SERVICE.MessageContracts.GeneralDetalleRQ request)
		{
			return null;
		}

        public virtual MessageContracts.GeneralRS Registrar_General(MessageContracts.GeneralRQ request)
        {
            return null;
        }

        public virtual MessageContracts.GeneralRS Modificar_General(MessageContracts.GeneralRQ request)
        {
            return null;
        }

        public virtual MessageContracts.GeneralRS Eliminar_General(MessageContracts.GeneralRQ request)
        {
            return null;
        }

        public virtual MessageContracts.GeneralRS Buscar_General(MessageContracts.GeneralRQ request)
        {
            return null;
        }

        public virtual MessageContracts.CargarClientesRS CargarClientes()
        {
            return null;
        }

        public virtual MessageContracts.CargaMunicipiosRS CargarMunicipios()
        {
            return null;
        }


        public virtual MessageContracts.CargarUsuariosRS CargarUsuarios()
        {
            return null;
        }

        public virtual MessageContracts.CargarCategoriasRS CargarCategorias()
        {
            return null;
        }

        public MessageContracts.CargarEventosRS CargarEventos()
        {
            return null;
        }

        #endregion   

    }
	
	public partial class PSDE_S : PSDE_SBase
	{
        public override MessageContracts.CategoriaUsuarioRS registrar_categoriausuario(MessageContracts.CategoriaUsuarioRQ request)
        {
            MessageContracts.CategoriaUsuarioRS res = new MessageContracts.CategoriaUsuarioRS();
            res.ResponseR = DataAccess.CatUsuario_DAL.insert(request.CategoriaUsuario);
            return res;
        }

        public override MessageContracts.CategoriaUsuarioRS modificar_categoriausuario(MessageContracts.CategoriaUsuarioRQ request)
        {
            MessageContracts.CategoriaUsuarioRS res = new MessageContracts.CategoriaUsuarioRS();
            res.ResponseR = DataAccess.CatUsuario_DAL.update(request.CategoriaUsuario);
            return res;
        }

        public override MessageContracts.CategoriaUsuarioRS eliminar_categoriausuario(MessageContracts.CategoriaUsuarioRQ request)
        {
            MessageContracts.CategoriaUsuarioRS res = new MessageContracts.CategoriaUsuarioRS();
            res.ResponseR = DataAccess.CatUsuario_DAL.delete(request.CategoriaUsuario);
            return res;
        }

        public override MessageContracts.FuenteFinanciamientoRS agregar_fuente_financiamiento(MessageContracts.FuenteFinanciamientoRQ request)
        {
            MessageContracts.FuenteFinanciamientoRS res = new MessageContracts.FuenteFinanciamientoRS();
            res.ResponseRS = DataAccess.FuenteFinanciamiento_DAL.insert(request.FuenteFinanciamiento);
            return res;
        }

        public override MessageContracts.FuenteFinanciamientoRS elminar_fuente_financiamiento(MessageContracts.FuenteFinanciamientoRQ request)
        {
            MessageContracts.FuenteFinanciamientoRS res = new MessageContracts.FuenteFinanciamientoRS();
            res.ResponseRS = DataAccess.FuenteFinanciamiento_DAL.delete(request.FuenteFinanciamiento);
            return res;
        }

        public override MessageContracts.FuenteFinanciamientoRS modificar_fuente_financiamiento(MessageContracts.FuenteFinanciamientoRQ request)
        {
            MessageContracts.FuenteFinanciamientoRS res = new MessageContracts.FuenteFinanciamientoRS();
            res.ResponseRS = DataAccess.FuenteFinanciamiento_DAL.update(request.FuenteFinanciamiento);
            return res;
        }

        public override MessageContracts.DepartamentoRS Agregar_Departamento(MessageContracts.DepartamentoRQ request)
        {
            MessageContracts.DepartamentoRS res = new MessageContracts.DepartamentoRS();
            res.ResponsiveRS = DataAccess.Departamento_DAL.insert(request.Departamento);
            return res;
        }

        public override MessageContracts.DepartamentoRS Eliminar_Departamento(MessageContracts.DepartamentoRQ request)
        {
            MessageContracts.DepartamentoRS res = new MessageContracts.DepartamentoRS();
            res.ResponsiveRS = DataAccess.Departamento_DAL.delete(request.Departamento);
            return res;
        }

        public override MessageContracts.DepartamentoRS Modificar_Departamento(MessageContracts.DepartamentoRQ request)
        {
            MessageContracts.DepartamentoRS res = new MessageContracts.DepartamentoRS();
            res.ResponsiveRS = DataAccess.Departamento_DAL.update(request.Departamento);
            return res;
        }

        public override MessageContracts.MunicipioRS Agregar_Municipio(MessageContracts.MunicipioRQ request)
        {
            MessageContracts.MunicipioRS res = new MessageContracts.MunicipioRS();
            res.ResponseRS = DataAccess.Municipio_DAL.insert(request.Municipio);
            return res;
        }

        public override MessageContracts.MunicipioRS Modificar_Municipio(MessageContracts.MunicipioRQ request)
        {
            MessageContracts.MunicipioRS res = new MessageContracts.MunicipioRS();
            res.ResponseRS = DataAccess.Municipio_DAL.update(request.Municipio);
            return res;
        }

        public override MessageContracts.MunicipioRS Eliminar_Municipio(MessageContracts.MunicipioRQ request)
        {
            MessageContracts.MunicipioRS res = new MessageContracts.MunicipioRS();
            res.ResponseRS = DataAccess.Municipio_DAL.delete(request.Municipio);
            return res;
        }

        public override MessageContracts.SucursalRS Agregar_Sucursal(MessageContracts.SucursalRQ request)
        {
            MessageContracts.SucursalRS res = new MessageContracts.SucursalRS();
            res.ResponseRS = DataAccess.Sucursal_DAL.insert(request.Sucursal);
            return res;
        }

        public override MessageContracts.SucursalRS Eliminar_Sucursal(MessageContracts.SucursalRQ request)
        {
            MessageContracts.SucursalRS res = new MessageContracts.SucursalRS();
            res.ResponseRS = DataAccess.Sucursal_DAL.delete(request.Sucursal);
            return res;
        }

        public override MessageContracts.SucursalRS Modificar_Sucursal(MessageContracts.SucursalRQ request)
        {
            MessageContracts.SucursalRS res = new MessageContracts.SucursalRS();
            res.ResponseRS = DataAccess.Sucursal_DAL.update(request.Sucursal);
            return res;
        }

        public override MessageContracts.IndicadorRS registrar_indicador(MessageContracts.IndicadorRQ request)
        {
            MessageContracts.IndicadorRS res = new MessageContracts.IndicadorRS();
            res.ResponseRS = DataAccess.Indicador_DAL.insert(request.Indicador);
            return res;
        }

        public override MessageContracts.IndicadorRS modificar_indicador(MessageContracts.IndicadorRQ request)
        {
            MessageContracts.IndicadorRS res = new MessageContracts.IndicadorRS();
            res.ResponseRS = DataAccess.Indicador_DAL.update(request.Indicador);
            return res;
        }

        public override MessageContracts.IndicadorRS eliminar_indicador(MessageContracts.IndicadorRQ request)
        {
            MessageContracts.IndicadorRS res = new MessageContracts.IndicadorRS();
            res.ResponseRS = DataAccess.Indicador_DAL.delete(request.Indicador);
            return res;
        }

        public override MessageContracts.SectorProductivoRS Agregar_SectorProductivo(MessageContracts.SectorProductivoRQ request)
        {
            MessageContracts.SectorProductivoRS res = new MessageContracts.SectorProductivoRS();
            res.ResponseRS = DataAccess.SectorProductivo_DAL.insert(request.SectorProductivo);
            return res;
        }

        public override MessageContracts.SectorProductivoRS Modificar_SectorProductivo(MessageContracts.SectorProductivoRQ request)
        {
            MessageContracts.SectorProductivoRS res = new MessageContracts.SectorProductivoRS();
            res.ResponseRS = DataAccess.SectorProductivo_DAL.update(request.SectorProductivo);
            return res;
        }

        public override MessageContracts.SectorProductivoRS Eliminar_SectorProductivo(MessageContracts.SectorProductivoRQ request)
        {
            MessageContracts.SectorProductivoRS res = new MessageContracts.SectorProductivoRS();
            res.ResponseRS = DataAccess.SectorProductivo_DAL.delete(request.SectorProductivo);
            return res;
        }

        public override MessageContracts.ProductoFinancierRS Agregar_ProductoFinanciero(MessageContracts.ProductoFinancieroRQ request)
        {
            MessageContracts.ProductoFinancierRS res = new MessageContracts.ProductoFinancierRS();
            res.ResponseRS = DataAccess.ProductoFinanciero_DAL.insert(request.ProductoFinanciero);
            return res;
        }

        public override MessageContracts.ProductoFinancierRS Modificar_ProductoFinanciero(MessageContracts.ProductoFinancieroRQ request)
        {
            MessageContracts.ProductoFinancierRS res = new MessageContracts.ProductoFinancierRS();
            res.ResponseRS = DataAccess.ProductoFinanciero_DAL.update(request.ProductoFinanciero);
            return res;
        }

        public override MessageContracts.ProductoFinancierRS Eliminar_ProductoFinanciero(MessageContracts.ProductoFinancieroRQ request)
        {
            MessageContracts.ProductoFinancierRS res = new MessageContracts.ProductoFinancierRS();
            res.ResponseRS = DataAccess.ProductoFinanciero_DAL.delete(request.ProductoFinanciero);
            return res;
        }

        public override MessageContracts.UsuarioRS Agregar_Usuario(MessageContracts.UsuarioRQ request)
        {
            MessageContracts.UsuarioRS res = new MessageContracts.UsuarioRS();
            res.ResponseRs = DataAccess.Usuario_DAL.insert(request.Usuario);
            return res;
        }

        public override MessageContracts.UsuarioRS Eliminar_Usuario(MessageContracts.UsuarioRQ request)
        {
            MessageContracts.UsuarioRS res = new MessageContracts.UsuarioRS();
            res.ResponseRs = DataAccess.Usuario_DAL.delete(request.Usuario);
            return res;
        }

        public override MessageContracts.UsuarioRS Modificar_Usuario(MessageContracts.UsuarioRQ request)
        {
            MessageContracts.UsuarioRS res = new MessageContracts.UsuarioRS();
            res.ResponseRs = DataAccess.Usuario_DAL.update(request.Usuario);
            return res;
        }

        public override MessageContracts.TipoEventoRS Agregar_TipoEvento(MessageContracts.TipoEventoRQ request)
        {
            MessageContracts.TipoEventoRS res = new MessageContracts.TipoEventoRS();
            res.ResponseRS = DataAccess.TipoEvento_DAL.insert(request.TipoEvento);
            return res;
        }

        public override MessageContracts.TipoEventoRS Modificar_TipoEvento(MessageContracts.TipoEventoRQ request)
        {
            MessageContracts.TipoEventoRS res = new MessageContracts.TipoEventoRS();
            res.ResponseRS = DataAccess.TipoEvento_DAL.update(request.TipoEvento);
            return res;
        }

        public override MessageContracts.TipoEventoRS Eliminar_TipoEvento(MessageContracts.TipoEventoRQ request)
        {
            MessageContracts.TipoEventoRS res = new MessageContracts.TipoEventoRS();
            res.ResponseRS = DataAccess.TipoEvento_DAL.delete(request.TipoEvento);
            return res;
        }

        public override MessageContracts.EventoRS Agregar_Evento(MessageContracts.EventoRQ request)
        {
            MessageContracts.EventoRS res = new MessageContracts.EventoRS();
            res.ResponseRS = DataAccess.Evento_DAL.insert(request.Evento);
            return res;
        }

        public override MessageContracts.EventoRS Modificar_Evento(MessageContracts.EventoRQ request)
        {
            MessageContracts.EventoRS res = new MessageContracts.EventoRS();
            res.ResponseRS = DataAccess.Evento_DAL.update(request.Evento);
            return res;
        }
        public override MessageContracts.EventoRS Eliminar_Evento(MessageContracts.EventoRQ request)
        {
            MessageContracts.EventoRS res = new MessageContracts.EventoRS();
            res.ResponseRS = DataAccess.Evento_DAL.delete(request.Evento);
            return res;
        }

        public override MessageContracts.ConvenioRS Agregar_Convenio(MessageContracts.ConvenioRQ request)
        {
            MessageContracts.ConvenioRS res = new MessageContracts.ConvenioRS();
            res.ResponseRS = DataAccess.Convenio_DAL.insert(request.Convenio);
            return res;
        }

        public override MessageContracts.ConvenioRS Modificar_Convenio(MessageContracts.ConvenioRQ request)
        {
            MessageContracts.ConvenioRS res = new MessageContracts.ConvenioRS();
            res.ResponseRS = DataAccess.Convenio_DAL.update(request.Convenio);
            return res;
        }

        public override MessageContracts.ConvenioRS Eliminar_Convenio(MessageContracts.ConvenioRQ request)
        {
            MessageContracts.ConvenioRS res = new MessageContracts.ConvenioRS();
            res.ResponseRS = DataAccess.Convenio_DAL.delete(request.Convenio);
            return res;
        }

        public override MessageContracts.DetalleConvenioRS Agregar_DetalleConvenio(MessageContracts.DetalleConvenioRQ request)
        {
            MessageContracts.DetalleConvenioRS res = new MessageContracts.DetalleConvenioRS();
            res.ResponseRS = DataAccess.DetalleConvenio_DAL.insert(request.DetalleConvenio);
            return res;
        }

        public override MessageContracts.DetalleConvenioRS Modificar_DetalleConvenio(MessageContracts.DetalleConvenioRQ request)
        {
            MessageContracts.DetalleConvenioRS res = new MessageContracts.DetalleConvenioRS();
            res.ResponseRS = DataAccess.DetalleConvenio_DAL.update(request.DetalleConvenio);
            return res;
        }

        public override MessageContracts.DetalleConvenioRS Eliminar_DetalleConvenio(MessageContracts.DetalleConvenioRQ request)
        {
            MessageContracts.DetalleConvenioRS res = new MessageContracts.DetalleConvenioRS();
            res.ResponseRS = DataAccess.DetalleConvenio_DAL.delete(request.DetalleConvenio);
            return res;
        }

        public override MessageContracts.FincaRS Agregar_Finca(MessageContracts.FincaRQ request)
        {
            MessageContracts.FincaRS res = new MessageContracts.FincaRS();
            res.ResponseRS = DataAccess.Finca_DAL.insert(request.Finca);
            return res;
        }

        public override MessageContracts.FincaRS Modificar_Finca(MessageContracts.FincaRQ request)
        {
            MessageContracts.FincaRS res = new MessageContracts.FincaRS();
            res.ResponseRS = DataAccess.Finca_DAL.update(request.Finca);
            return res;
        }

        public override MessageContracts.FincaRS Eliminar_Finca(MessageContracts.FincaRQ request)
        {
            MessageContracts.FincaRS res = new MessageContracts.FincaRS();
            res.ResponseRS = DataAccess.Finca_DAL.delete(request.Finca);
            return res;
        }

        public override MessageContracts.HistorialRS Agregar_Historial(MessageContracts.HistorialRQ request)
        {
            MessageContracts.HistorialRS res = new MessageContracts.HistorialRS();
            res.ResponseRS = DataAccess.Hisotial_DAL.insert(request.Historial);
            return res;
        }

        public override MessageContracts.HistorialRS Modificar_Historial(MessageContracts.HistorialRQ request)
        {
            MessageContracts.HistorialRS res = new MessageContracts.HistorialRS();
            res.ResponseRS = DataAccess.Hisotial_DAL.update(request.Historial);
            return res;
        }

        public override MessageContracts.HistorialRS Eliminar_Historial(MessageContracts.HistorialRQ request)
        {
            MessageContracts.HistorialRS res = new MessageContracts.HistorialRS();
            res.ResponseRS = DataAccess.Hisotial_DAL.delete(request.Historial);
            return res;
        }

        public override MessageContracts.GeneralDetalleRS registrar_general_detalle(MessageContracts.GeneralDetalleRQ request)
        {
            MessageContracts.GeneralDetalleRS res = new MessageContracts.GeneralDetalleRS();
            res.ResponseRS = DataAccess.GeneralDetalle_DAL.insert(request.GeneralDetalle);
            return res;
        }

        public override MessageContracts.GeneralDetalleRS modificar_general_detalle(MessageContracts.GeneralDetalleRQ request)
        {
            MessageContracts.GeneralDetalleRS res = new MessageContracts.GeneralDetalleRS();
            res.ResponseRS = DataAccess.GeneralDetalle_DAL.update(request.GeneralDetalle);
            return res;
        }

        public override MessageContracts.GeneralDetalleRS eliminar_general_detalle(MessageContracts.GeneralDetalleRQ request)
        {
            MessageContracts.GeneralDetalleRS res = new MessageContracts.GeneralDetalleRS();
            res.ResponseRS = DataAccess.GeneralDetalle_DAL.delete(request.GeneralDetalle);
            return res;
        }

        public override MessageContracts.CoordenadaRS Agregar_Coordenada(MessageContracts.CoordenadaRQ request)
        {
            MessageContracts.CoordenadaRS res = new MessageContracts.CoordenadaRS();
            res.ResponseRS = DataAccess.Coordenada_DAL.insert(request.Coordenada);
            return res;
        }

        public override MessageContracts.CoordenadaRS Modificar_Coordenada(MessageContracts.CoordenadaRQ request)
        {
            MessageContracts.CoordenadaRS res = new MessageContracts.CoordenadaRS();
            res.ResponseRS = DataAccess.Coordenada_DAL.update(request.Coordenada);
            return res;
        }

        public override MessageContracts.CoordenadaRS Eliminar_Coordenada(MessageContracts.CoordenadaRQ request)
        {
            MessageContracts.CoordenadaRS res = new MessageContracts.CoordenadaRS();
            res.ResponseRS = DataAccess.Coordenada_DAL.delete(request.Coordenada);
            return res;
        }

        public override MessageContracts.ClienteRS Agregar_Cliente(MessageContracts.ClienteRQ request)
        {
            MessageContracts.ClienteRS res = new MessageContracts.ClienteRS();
            res.ResponseRS = DataAccess.Cliente_DAL.insert(request.Cliente);
            return res;
        }

        public override MessageContracts.ClienteRS Modificar_Cliente(MessageContracts.ClienteRQ request)
        {
            MessageContracts.ClienteRS res = new MessageContracts.ClienteRS();
            res.ResponseRS = DataAccess.Cliente_DAL.update(request.Cliente);
            return res;
        }

        public override MessageContracts.ClienteRS Eliminar_Cliente(MessageContracts.ClienteRQ request)
        {
            MessageContracts.ClienteRS res = new MessageContracts.ClienteRS();
            res.ResponseRS = DataAccess.Cliente_DAL.delete(request.Cliente);
            return res;
        }

        public override MessageContracts.ContratoRS Agregar_Contrato(MessageContracts.ContratoRQ request)
        {
            MessageContracts.ContratoRS res = new MessageContracts.ContratoRS();
            res.ResponseRS = DataAccess.Contrato_DAL.insert(request.Contrato);
            return res;
        }

        public override MessageContracts.ContratoRS Modificar_Contrato(MessageContracts.ContratoRQ request)
        {
            MessageContracts.ContratoRS res = new MessageContracts.ContratoRS();
            res.ResponseRS = DataAccess.Contrato_DAL.update(request.Contrato);
            return res;
        }

        public override MessageContracts.ContratoRS Eliminar_Contrato(MessageContracts.ContratoRQ request)
        {
            MessageContracts.ContratoRS res = new MessageContracts.ContratoRS();
            res.ResponseRS = DataAccess.Contrato_DAL.delete(request.Contrato);
            return res;
        }

        public override MessageContracts.GeneralRS Registrar_General(MessageContracts.GeneralRQ request)
        {
            MessageContracts.GeneralRS res = new MessageContracts.GeneralRS();
            res.ResponseRS = DataAccess.General_DAL.insert(request.General);
            return res;
        }

        public override MessageContracts.GeneralRS Modificar_General(MessageContracts.GeneralRQ request)
        {
            MessageContracts.GeneralRS res = new MessageContracts.GeneralRS();
            res.ResponseRS = DataAccess.General_DAL.update(request.General);
            return res;
        }

        public override MessageContracts.GeneralRS Eliminar_General(MessageContracts.GeneralRQ request)
        {
            MessageContracts.GeneralRS res = new MessageContracts.GeneralRS();
            res.ResponseRS = DataAccess.General_DAL.delete(request.General);
            return res;
        }

        public override PSDE_SERVICE.MessageContracts.CargarClientesRS CargarClientes()
        {
            PSDE_SERVICE.MessageContracts.CargarClientesRS res = new PSDE_SERVICE.MessageContracts.CargarClientesRS();
            res.Clientes = DataAccess.Cliente_DAL.CargarClientes();
            return res;
        }

        public override MessageContracts.CargarUsuariosRS CargarUsuarios()
        {
            PSDE_SERVICE.MessageContracts.CargarUsuariosRS res = new MessageContracts.CargarUsuariosRS();
            res.Usuarios = DataAccess.Usuario_DAL.CargarUsuarios();
            return res;
        }

        public override MessageContracts.CargaMunicipiosRS CargarMunicipios()
        {
            PSDE_SERVICE.MessageContracts.CargaMunicipiosRS res = new MessageContracts.CargaMunicipiosRS();
            res.Municipios = DataAccess.Municipio_DAL.listaMunicipios();
            return res;
        }

        public override MessageContracts.CargarCategoriasRS CargarCategorias()
        {
            PSDE_SERVICE.MessageContracts.CargarCategoriasRS res = new MessageContracts.CargarCategoriasRS();
            res.Categorias = DataAccess.CatUsuario_DAL.CargarCategorias();
            return res;
        }

        
	}
	
}

