//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - CategoriaUsuario
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "CategoriaUsuario")]
	public partial class CategoriaUsuario 
	{
		private int idCategoria;
		private string nombre;
		private string descripcion;
		
		[WcfSerialization::DataMember(Name = "IdCategoria", IsRequired = false, Order = 0)]
		public int IdCategoria
		{
		  get { return idCategoria; }
		  set { idCategoria = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Descripcion", IsRequired = false, Order = 2)]
		public string Descripcion
		{
		  get { return descripcion; }
		  set { descripcion = value; }
		}				
	}
}

