//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Cliente
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Cliente")]
	public partial class Cliente 
	{
		private int idCliente;
		private string nombre;
		private string apellido;
		private System.Nullable<bool> sexo;
		private string cedula;
		private System.Nullable<int> edad;
		private string telefono;
		private string direccion;
		private string comarca;
		private string codWeb;
		private int codMunicipio;
		
		[WcfSerialization::DataMember(Name = "IdCliente", IsRequired = false, Order = 0)]
		public int IdCliente
		{
		  get { return idCliente; }
		  set { idCliente = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Apellido", IsRequired = false, Order = 2)]
		public string Apellido
		{
		  get { return apellido; }
		  set { apellido = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sexo", IsRequired = false, Order = 3)]
		public System.Nullable<bool> Sexo
		{
		  get { return sexo; }
		  set { sexo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Cedula", IsRequired = false, Order = 4)]
		public string Cedula
		{
		  get { return cedula; }
		  set { cedula = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Edad", IsRequired = false, Order = 5)]
		public System.Nullable<int> Edad
		{
		  get { return edad; }
		  set { edad = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Telefono", IsRequired = false, Order = 6)]
		public string Telefono
		{
		  get { return telefono; }
		  set { telefono = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Direccion", IsRequired = false, Order = 7)]
		public string Direccion
		{
		  get { return direccion; }
		  set { direccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Comarca", IsRequired = false, Order = 8)]
		public string Comarca
		{
		  get { return comarca; }
		  set { comarca = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodWeb", IsRequired = false, Order = 9)]
		public string CodWeb
		{
		  get { return codWeb; }
		  set { codWeb = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodMunicipio", IsRequired = false, Order = 10)]
		public int CodMunicipio
		{
		  get { return codMunicipio; }
		  set { codMunicipio = value; }
		}				
	}
}

