//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Contrato
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Contrato")]
	public partial class Contrato 
	{
		private int idContrato;
		private int codContrato;
		private int codCliente;
		private int codUsuario;
		private int codSucursal;
		private int codConvenio;
		private int codSectorProductivo;
		private int codProductoFinanciero;
		private double montoOtorgado;
		private System.DateTime fechaDesembolso;
		
		[WcfSerialization::DataMember(Name = "IdContrato", IsRequired = false, Order = 0)]
		public int IdContrato
		{
		  get { return idContrato; }
		  set { idContrato = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodContrato", IsRequired = false, Order = 1)]
		public int CodContrato
		{
		  get { return codContrato; }
		  set { codContrato = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodCliente", IsRequired = false, Order = 2)]
		public int CodCliente
		{
		  get { return codCliente; }
		  set { codCliente = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodUsuario", IsRequired = false, Order = 3)]
		public int CodUsuario
		{
		  get { return codUsuario; }
		  set { codUsuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodSucursal", IsRequired = false, Order = 4)]
		public int CodSucursal
		{
		  get { return codSucursal; }
		  set { codSucursal = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodConvenio", IsRequired = false, Order = 5)]
		public int CodConvenio
		{
		  get { return codConvenio; }
		  set { codConvenio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodSectorProductivo", IsRequired = false, Order = 6)]
		public int CodSectorProductivo
		{
		  get { return codSectorProductivo; }
		  set { codSectorProductivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodProductoFinanciero", IsRequired = false, Order = 7)]
		public int CodProductoFinanciero
		{
		  get { return codProductoFinanciero; }
		  set { codProductoFinanciero = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoOtorgado", IsRequired = false, Order = 8)]
		public double MontoOtorgado
		{
		  get { return montoOtorgado; }
		  set { montoOtorgado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaDesembolso", IsRequired = false, Order = 9)]
		public System.DateTime FechaDesembolso
		{
		  get { return fechaDesembolso; }
		  set { fechaDesembolso = value; }
		}				
	}
}

