//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Convenio
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Convenio")]
	public partial class Convenio 
	{
		private int idC;
		private System.Nullable<System.DateTime> fechaInicio;
		private System.Nullable<System.DateTime> fechaFinal;
		private System.Nullable<int> totalClientes;
		private System.Nullable<double> montoFF;
		private System.Nullable<double> montoP;
		
		[WcfSerialization::DataMember(Name = "IdC", IsRequired = false, Order = 0)]
		public int IdC
		{
		  get { return idC; }
		  set { idC = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicio", IsRequired = false, Order = 1)]
		public System.Nullable<System.DateTime> FechaInicio
		{
		  get { return fechaInicio; }
		  set { fechaInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFinal", IsRequired = false, Order = 2)]
		public System.Nullable<System.DateTime> FechaFinal
		{
		  get { return fechaFinal; }
		  set { fechaFinal = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TotalClientes", IsRequired = false, Order = 3)]
		public System.Nullable<int> TotalClientes
		{
		  get { return totalClientes; }
		  set { totalClientes = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoFF", IsRequired = false, Order = 4)]
		public System.Nullable<double> MontoFF
		{
		  get { return montoFF; }
		  set { montoFF = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoP", IsRequired = false, Order = 5)]
		public System.Nullable<double> MontoP
		{
		  get { return montoP; }
		  set { montoP = value; }
		}				
	}
}

