//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Coordenada
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Coordenada")]
	public partial class Coordenada 
	{
		private int idCoordenada;
		private string coordenada_X_UTM;
		private string coordenada_Y_UTM;
		private string coordenada_X_GMS;
		private string coordenada_Y_GMS;
		
		[WcfSerialization::DataMember(Name = "IdCoordenada", IsRequired = false, Order = 0)]
		public int IdCoordenada
		{
		  get { return idCoordenada; }
		  set { idCoordenada = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_X_UTM", IsRequired = false, Order = 1)]
		public string Coordenada_X_UTM
		{
		  get { return coordenada_X_UTM; }
		  set { coordenada_X_UTM = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_Y_UTM", IsRequired = false, Order = 2)]
		public string Coordenada_Y_UTM
		{
		  get { return coordenada_Y_UTM; }
		  set { coordenada_Y_UTM = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_X_GMS", IsRequired = false, Order = 3)]
		public string Coordenada_X_GMS
		{
		  get { return coordenada_X_GMS; }
		  set { coordenada_X_GMS = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_Y_GMS", IsRequired = false, Order = 4)]
		public string Coordenada_Y_GMS
		{
		  get { return coordenada_Y_GMS; }
		  set { coordenada_Y_GMS = value; }
		}				
	}
}

