//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - DetalleConvenio
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "DetalleConvenio")]
	public partial class DetalleConvenio 
	{
		private int idDC;
		private int codConvenio;
		private int codFuenteF;
		private int codProducto;
		private System.Nullable<int> numeroClientes;
		private System.Nullable<double> inversionCliente;
		
		[WcfSerialization::DataMember(Name = "IdDC", IsRequired = false, Order = 0)]
		public int IdDC
		{
		  get { return idDC; }
		  set { idDC = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodConvenio", IsRequired = false, Order = 1)]
		public int CodConvenio
		{
		  get { return codConvenio; }
		  set { codConvenio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodFuenteF", IsRequired = false, Order = 2)]
		public int CodFuenteF
		{
		  get { return codFuenteF; }
		  set { codFuenteF = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodProducto", IsRequired = false, Order = 3)]
		public int CodProducto
		{
		  get { return codProducto; }
		  set { codProducto = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NumeroClientes", IsRequired = false, Order = 4)]
		public System.Nullable<int> NumeroClientes
		{
		  get { return numeroClientes; }
		  set { numeroClientes = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "InversionCliente", IsRequired = false, Order = 5)]
		public System.Nullable<double> InversionCliente
		{
		  get { return inversionCliente; }
		  set { inversionCliente = value; }
		}				
	}
}

