//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Evento
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Evento")]
	public partial class Evento 
	{
		private int idEvento;
		private int codTipoEvento;
		private string tituloEvento;
		
		[WcfSerialization::DataMember(Name = "IdEvento", IsRequired = false, Order = 0)]
		public int IdEvento
		{
		  get { return idEvento; }
		  set { idEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodTipoEvento", IsRequired = false, Order = 1)]
		public int CodTipoEvento
		{
		  get { return codTipoEvento; }
		  set { codTipoEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TituloEvento", IsRequired = false, Order = 2)]
		public string TituloEvento
		{
		  get { return tituloEvento; }
		  set { tituloEvento = value; }
		}				
	}
}

