//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Finca
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Finca")]
	public partial class Finca 
	{
		private int idFinca;
		private double haTotalFinca;
		private double haEfectiva;
		private double usoActualSuelo;
		private int codCliente;
		private string coordenada_X_UTM;
		private string coordenada_Y_UTM;
		private string coordenada_X_GMS;
		private string coordenada_Y_GMS;
		
		[WcfSerialization::DataMember(Name = "IdFinca", IsRequired = false, Order = 0)]
		public int IdFinca
		{
		  get { return idFinca; }
		  set { idFinca = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HaTotalFinca", IsRequired = false, Order = 1)]
		public double HaTotalFinca
		{
		  get { return haTotalFinca; }
		  set { haTotalFinca = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HaEfectiva", IsRequired = false, Order = 2)]
		public double HaEfectiva
		{
		  get { return haEfectiva; }
		  set { haEfectiva = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "UsoActualSuelo", IsRequired = false, Order = 3)]
		public double UsoActualSuelo
		{
		  get { return usoActualSuelo; }
		  set { usoActualSuelo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodCliente", IsRequired = false, Order = 4)]
		public int CodCliente
		{
		  get { return codCliente; }
		  set { codCliente = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_X_UTM", IsRequired = false, Order = 5)]
		public string Coordenada_X_UTM
		{
		  get { return coordenada_X_UTM; }
		  set { coordenada_X_UTM = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_Y_UTM", IsRequired = false, Order = 6)]
		public string Coordenada_Y_UTM
		{
		  get { return coordenada_Y_UTM; }
		  set { coordenada_Y_UTM = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_X_GMS", IsRequired = false, Order = 7)]
		public string Coordenada_X_GMS
		{
		  get { return coordenada_X_GMS; }
		  set { coordenada_X_GMS = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Coordenada_Y_GMS", IsRequired = false, Order = 8)]
		public string Coordenada_Y_GMS
		{
		  get { return coordenada_Y_GMS; }
		  set { coordenada_Y_GMS = value; }
		}				
	}
}

