//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - GeneralDetalle
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "GeneralDetalle")]
	public partial class GeneralDetalle 
	{
		private int id;
		private int idIndicador;
		private double avanceCuantitativo;
		private int codEvento;
		private System.DateTime fecha;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public int Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdIndicador", IsRequired = false, Order = 1)]
		public int IdIndicador
		{
		  get { return idIndicador; }
		  set { idIndicador = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AvanceCuantitativo", IsRequired = false, Order = 2)]
		public double AvanceCuantitativo
		{
		  get { return avanceCuantitativo; }
		  set { avanceCuantitativo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CodEvento", IsRequired = false, Order = 3)]
		public int CodEvento
		{
		  get { return codEvento; }
		  set { codEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Fecha", IsRequired = false, Order = 4)]
		public System.DateTime Fecha
		{
		  get { return fecha; }
		  set { fecha = value; }
		}				
	}
}

