//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Historial
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Historial")]
	public partial class Historial 
	{
		private int id;
		private System.DateTime fechaInicio;
		private System.DateTime fechaFin;
		private int idUsuario;
		
		[WcfSerialization::DataMember(Name = "Id", IsRequired = false, Order = 0)]
		public int Id
		{
		  get { return id; }
		  set { id = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicio", IsRequired = false, Order = 1)]
		public System.DateTime FechaInicio
		{
		  get { return fechaInicio; }
		  set { fechaInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFin", IsRequired = false, Order = 2)]
		public System.DateTime FechaFin
		{
		  get { return fechaFin; }
		  set { fechaFin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "IdUsuario", IsRequired = false, Order = 3)]
		public int IdUsuario
		{
		  get { return idUsuario; }
		  set { idUsuario = value; }
		}				
	}
}

