//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Indicador
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Indicador")]
	public partial class Indicador 
	{
		private int idIndicador;
		private string nombreIndicador;
		private double avanceCuantitativo;
		private double avancePorcentaje;
		private System.DateTime fechaActualizacion;
		
		[WcfSerialization::DataMember(Name = "IdIndicador", IsRequired = false, Order = 0)]
		public int IdIndicador
		{
		  get { return idIndicador; }
		  set { idIndicador = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "NombreIndicador", IsRequired = false, Order = 1)]
		public string NombreIndicador
		{
		  get { return nombreIndicador; }
		  set { nombreIndicador = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AvanceCuantitativo", IsRequired = false, Order = 2)]
		public double AvanceCuantitativo
		{
		  get { return avanceCuantitativo; }
		  set { avanceCuantitativo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "AvancePorcentaje", IsRequired = false, Order = 3)]
		public double AvancePorcentaje
		{
		  get { return avancePorcentaje; }
		  set { avancePorcentaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaActualizacion", IsRequired = false, Order = 4)]
		public System.DateTime FechaActualizacion
		{
		  get { return fechaActualizacion; }
		  set { fechaActualizacion = value; }
		}				
	}
}

