//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Indicadores
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC")]
	public partial class Indicadores : System.Collections.Generic.List<Indicador>
	{
	}
}

