//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - ListaVistaUsuario
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "ListaVistaUsuario")]
	public partial class ListaVistaUsuario 
	{
		private int idUsuario;
		private string nombre;
		private string apellido;
		private string telefono;
		private string direccion;
		private string celular;
		private string cedula;
		private string responsable;
		private string categoria;
		
		[WcfSerialization::DataMember(Name = "IdUsuario", IsRequired = false, Order = 0)]
		public int IdUsuario
		{
		  get { return idUsuario; }
		  set { idUsuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Apellido", IsRequired = false, Order = 2)]
		public string Apellido
		{
		  get { return apellido; }
		  set { apellido = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Telefono", IsRequired = false, Order = 3)]
		public string Telefono
		{
		  get { return telefono; }
		  set { telefono = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Direccion", IsRequired = false, Order = 4)]
		public string Direccion
		{
		  get { return direccion; }
		  set { direccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Celular", IsRequired = false, Order = 5)]
		public string Celular
		{
		  get { return celular; }
		  set { celular = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Cedula", IsRequired = false, Order = 6)]
		public string Cedula
		{
		  get { return cedula; }
		  set { cedula = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Responsable", IsRequired = false, Order = 7)]
		public string Responsable
		{
		  get { return responsable; }
		  set { responsable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Categoria", IsRequired = false, Order = 8)]
		public string Categoria
		{
		  get { return categoria; }
		  set { categoria = value; }
		}				
	}
}

