//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - ListaVistaCliente
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "ListaVistaCliente")]
	public partial class ListaVistaCliente 
	{
		private int idCliente;
		private string nombre;
		private string cedula;
		private string genero;
		private System.Nullable<int> edad;
		private string telefono;
		private string direccion;
		private string comarca;
		private string municipio;
		private string codigo_Web;
		private string apellido;
		
		[WcfSerialization::DataMember(Name = "IdCliente", IsRequired = false, Order = 0)]
		public int IdCliente
		{
		  get { return idCliente; }
		  set { idCliente = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Cedula", IsRequired = false, Order = 3)]
		public string Cedula
		{
		  get { return cedula; }
		  set { cedula = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Genero", IsRequired = false, Order = 4)]
		public string Genero
		{
		  get { return genero; }
		  set { genero = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Edad", IsRequired = false, Order = 5)]
		public System.Nullable<int> Edad
		{
		  get { return edad; }
		  set { edad = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Telefono", IsRequired = false, Order = 6)]
		public string Telefono
		{
		  get { return telefono; }
		  set { telefono = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Direccion", IsRequired = false, Order = 7)]
		public string Direccion
		{
		  get { return direccion; }
		  set { direccion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Comarca", IsRequired = false, Order = 8)]
		public string Comarca
		{
		  get { return comarca; }
		  set { comarca = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Municipio", IsRequired = false, Order = 9)]
		public string Municipio
		{
		  get { return municipio; }
		  set { municipio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Codigo_Web", IsRequired = false, Order = 10)]
		public string Codigo_Web
		{
		  get { return codigo_Web; }
		  set { codigo_Web = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Apellido", IsRequired = false, Order = 2)]
		public string Apellido
		{
		  get { return apellido; }
		  set { apellido = value; }
		}				
	}
}

