//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - ListaVistaEvento
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "ListaVistaEvento")]
	public partial class ListaVistaEvento 
	{
		private string nombre;
		private string apellido;
		private string tituloDelEvento;
		private string tipoDeEvento;
		private int evetnosPactados;
		private int eventosEjecutados;
		private System.DateTime fechaInicio;
		private System.DateTime fechaFin;
		private string estado;
		private string otros;
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 0)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Apellido", IsRequired = false, Order = 1)]
		public string Apellido
		{
		  get { return apellido; }
		  set { apellido = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TituloDelEvento", IsRequired = false, Order = 2)]
		public string TituloDelEvento
		{
		  get { return tituloDelEvento; }
		  set { tituloDelEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TipoDeEvento", IsRequired = false, Order = 3)]
		public string TipoDeEvento
		{
		  get { return tipoDeEvento; }
		  set { tipoDeEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EvetnosPactados", IsRequired = false, Order = 4)]
		public int EvetnosPactados
		{
		  get { return evetnosPactados; }
		  set { evetnosPactados = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EventosEjecutados", IsRequired = false, Order = 5)]
		public int EventosEjecutados
		{
		  get { return eventosEjecutados; }
		  set { eventosEjecutados = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicio", IsRequired = false, Order = 6)]
		public System.DateTime FechaInicio
		{
		  get { return fechaInicio; }
		  set { fechaInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFin", IsRequired = false, Order = 7)]
		public System.DateTime FechaFin
		{
		  get { return fechaFin; }
		  set { fechaFin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 8)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Otros", IsRequired = false, Order = 9)]
		public string Otros
		{
		  get { return otros; }
		  set { otros = value; }
		}				
	}
}

