//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - Sucursal
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "Sucursal")]
	public partial class Sucursal 
	{
		private int idSucursal;
		private string nombre;
		private string responsableField;
		private System.Nullable<int> idMunicipioField;
		private string telefonoField;
		
		[WcfSerialization::DataMember(Name = "IdSucursal", IsRequired = false, Order = 0)]
		public int IdSucursal
		{
		  get { return idSucursal; }
		  set { idSucursal = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 1)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "responsable", IsRequired = false, Order = 2)]
		public string responsable
		{
		  get { return responsableField; }
		  set { responsableField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idMunicipio", IsRequired = false, Order = 3)]
		public System.Nullable<int> idMunicipio
		{
		  get { return idMunicipioField; }
		  set { idMunicipioField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "telefono", IsRequired = false, Order = 4)]
		public string telefono
		{
		  get { return telefonoField; }
		  set { telefonoField = value; }
		}				
	}
}

