//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace PSDE_SERVICE.DataContracts
{
	/// <summary>
	/// Data Contract Class - TipoEvento
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://PSDE.Model/2013/PSDE_DC", Name = "TipoEvento")]
	public partial class TipoEvento 
	{
		private int idTipoEvento;
		private string evento;
		
		[WcfSerialization::DataMember(Name = "IdTipoEvento", IsRequired = false, Order = 0)]
		public int IdTipoEvento
		{
		  get { return idTipoEvento; }
		  set { idTipoEvento = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Evento", IsRequired = false, Order = 1)]
		public string Evento
		{
		  get { return evento; }
		  set { evento = value; }
		}				
	}
}

